# Generated by Django 5.2.1 on 2025-05-13 08:55

import django.db.models.deletion
import django.utils.timezone
import djgeojson.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60, verbose_name='nome')),
                ('icon', models.CharField(max_length=20, null=True, verbose_name='icona')),
                ('slug', models.SlugField(unique=True)),
            ],
            options={
                'verbose_name': 'categoria',
                'verbose_name_plural': 'categorie',
            },
        ),
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60, verbose_name='titolo')),
                ('description', models.TextField(blank=True, null=True, verbose_name='info')),
                ('evaluation', models.CharField(blank=True, choices=[('R', 'Negativa'), ('Y', 'Mista'), ('G', 'Positiva')], max_length=1, null=True, verbose_name='valutazione')),
                ('published', models.BooleanField(default=False, verbose_name='pubblicata')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='djeography.category', verbose_name='categoria')),
            ],
            options={
                'verbose_name': 'segnalazione',
                'verbose_name_plural': 'segnalazioni',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typology', models.CharField(choices=[('P', 'numero di telefono'), ('E', 'e-mail'), ('S', 'sito')], max_length=2, verbose_name='tipo')),
                ('contact', models.CharField(max_length=60, verbose_name='contatto')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeography.entity')),
            ],
            options={
                'verbose_name': 'contatto',
                'verbose_name_plural': 'contatti',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('road', models.CharField(blank=True, max_length=120, null=True, verbose_name='via/piazza')),
                ('number', models.CharField(blank=True, max_length=20, null=True, verbose_name='numero civico')),
                ('city', models.CharField(max_length=60, verbose_name='città')),
                ('province', models.CharField(choices=[('AG', 'Agrigento'), ('AL', 'Alessandria'), ('AN', 'Ancona'), ('AO', 'Aosta'), ('AR', 'Arezzo'), ('AP', 'Ascoli Piceno'), ('AT', 'Asti'), ('AV', 'Avellino'), ('BA', 'Bari'), ('BT', 'Barletta-Andria-Trani'), ('BL', 'Belluno'), ('BN', 'Benevento'), ('BG', 'Bergamo'), ('BI', 'Biella'), ('BO', 'Bologna'), ('BZ', 'Bolzano'), ('BS', 'Brescia'), ('BR', 'Brindisi'), ('CA', 'Cagliari'), ('CL', 'Caltanissetta'), ('CB', 'Campobasso'), ('CE', 'Caserta'), ('CT', 'Catania'), ('CZ', 'Catanzaro'), ('CH', 'Chieti'), ('CO', 'Como'), ('CS', 'Cosenza'), ('CR', 'Cremona'), ('KR', 'Crotone'), ('CN', 'Cuneo'), ('EN', 'Enna'), ('FM', 'Fermo'), ('FE', 'Ferrara'), ('FI', 'Firenze'), ('FG', 'Foggia'), ('FC', 'Forlì-Cesena'), ('FR', 'Frosinone'), ('GE', 'Genova'), ('GO', 'Gorizia'), ('GR', 'Grosseto'), ('IM', 'Imperia'), ('IS', 'Isernia'), ('SP', 'La Spezia'), ('AQ', "L'Aquila"), ('LT', 'Latina'), ('LE', 'Lecce'), ('LC', 'Lecco'), ('LI', 'Livorno'), ('LO', 'Lodi'), ('LU', 'Lucca'), ('MC', 'Macerata'), ('MN', 'Mantova'), ('MS', 'Massa-Carrara'), ('MT', 'Matera'), ('ME', 'Messina'), ('MI', 'Milano'), ('MO', 'Modena'), ('MB', 'Monza Brianza'), ('NA', 'Napoli'), ('NO', 'Novara'), ('NU', 'Nuoro'), ('OR', 'Oristano'), ('PD', 'Padova'), ('PA', 'Palermo'), ('PR', 'Parma'), ('PV', 'Pavia'), ('PG', 'Perugia'), ('PU', 'Pesaro e Urbino'), ('PE', 'Pescara'), ('PC', 'Piacenza'), ('PI', 'Pisa'), ('PT', 'Pistoia'), ('PN', 'Pordenone'), ('PZ', 'Potenza'), ('PO', 'Prato'), ('RG', 'Ragusa'), ('RA', 'Ravenna'), ('RC', 'Reggio Calabria'), ('RE', 'Reggio Emilia'), ('RI', 'Rieti'), ('RN', 'Rimini'), ('RM', 'Roma'), ('RO', 'Rovigo'), ('SA', 'Salerno'), ('SS', 'Sassari'), ('SV', 'Savona'), ('SI', 'Siena'), ('SR', 'Siracusa'), ('SO', 'Sondrio'), ('SU', 'Sud Sardegna'), ('TA', 'Taranto'), ('TE', 'Teramo'), ('TR', 'Terni'), ('TO', 'Torino'), ('TP', 'Trapani'), ('TN', 'Trento'), ('TV', 'Treviso'), ('TS', 'Trieste'), ('UD', 'Udine'), ('VA', 'Varese'), ('VE', 'Venezia'), ('VB', 'Verbano-Cusio-Ossola'), ('VC', 'Vercelli'), ('VR', 'Verona'), ('VV', 'Vibo Valentia'), ('VI', 'Vicenza'), ('VT', 'Viterbo')], max_length=2, verbose_name='provincia')),
                ('coords', djgeojson.fields.PointField()),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeography.entity')),
            ],
            options={
                'verbose_name': 'indirizzo',
                'verbose_name_plural': 'indirizzi',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='titolo')),
                ('body', models.TextField(blank=True, null=True, verbose_name='testo')),
                ('date_added', models.DateField(default=django.utils.timezone.now, verbose_name='data')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='djeography.entity')),
            ],
            options={
                'verbose_name': 'testimonianza',
                'verbose_name_plural': 'testimonianze',
                'get_latest_by': 'date_added',
            },
        ),
    ]
