# Generated by Django 5.2.1 on 2025-07-08 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djeography', '0002_create_default_eval_levels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.CharField(blank=True, help_text='inserisci il nome di un\'icona da <a href="https://fontawesome.com/search?ic=free" target="_blank">https://fontawesome.com/search?ic=free</a>', max_length=20, verbose_name='icona'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=models.TextField(blank=True, verbose_name='info'),
        ),
        migrations.AlterField(
            model_name='report',
            name='body',
            field=models.TextField(blank=True, verbose_name='testo'),
        ),
    ]
