# Generated by Django 5.2.1 on 2025-05-16 17:55

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('djeography', '0002_alter_entity_evaluation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='info'),
        ),
    ]
